### PR TITLE
Ignore Underscores within Brackets of Plasmid FASTA Record ID

### LINKED ISSUE #158: Some plasmidfinder blast results causing staramr to crash
# Issue

When running staramr where some plasmidfinder incompatibility factors are detected causes staramr to crash with the following message:

```
2022-10-24 11:47:20 ERROR: Index length not within range, for [rep21_24_rep(CN1_plasmid2)_NC_022227]
Traceback (most recent call last):
  File "/home/CSCScience.ca/apetkau/miniconda3/envs/staramr-0.9.0/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/home/CSCScience.ca/apetkau/miniconda3/envs/staramr-0.9.0/lib/python3.10/site-packages/staramr/subcommand/Search.py", line 467, in run
...
  File "/home/CSCScience.ca/apetkau/miniconda3/envs/staramr-0.9.0/lib/python3.10/site-packages/staramr/blast/results/plasmidfinder/PlasmidfinderHitHSP.py", line 56, in __init__
    raise Exception("Index length not within range, for [" + self.get_amr_gene_id() + "]")
Exception: Index length not within range, for [rep21_24_rep(CN1_plasmid2)_NC_022227]
```

# Testing

To test this out, please download the following test file:

* [test-plasmid-rep.zip](https://github.com/phac-nml/staramr/files/9853723/test-plasmid-rep.zip)

Unzip this file and try running the following:

```bash
staramr search -o out test-plasmid-rep.fsa
```

You should receive the above error message.

### PR DESCRIPTION
**Pull request by emarinier**
Fixes #158 

Solution is provided by this StackOverflow post: https://stackoverflow.com/a/26634150

### CODE REVIEW

**Review by apetkau — CHANGES_REQUESTED** [review]
Thanks @emarinier for the quick fix 😄 

Could you add a test case in https://github.com/phac-nml/staramr/blob/development/staramr/tests/integration/detection/test_AMRDetectionPlasmid.py ? You can use the same file from this github issue.

**Comment by apetkau** [comment]
Also, could you add a message to `CHANGELOG.md` about this (make a new section for version 0.9.1).

**Comment by emarinier** [comment]
Okay, it should be good to go now.

**Review by apetkau — APPROVED** [review]
Okay, thanks so much Eric. This is perfect.

I also checked what PlasmidFinder does in this case, and here is the results:

image

So, it's the same as what we're doing. So it all looks good.

**Pull request merged**
